### ISSUE TITLE
[Issue]: install latest not handled and leaks unnecessary info

### ISSUE THREAD

**Issue by Nasfame** [coreybutler/nvm-windows#1077]
### What happened?

```
 nvm install latest
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x1149e0c0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:790 +0x220
main.install({0x1140a0e0, 0x6}, {0x29fa65, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:302 +0x35d
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69

``

### What did you expect to happen?

Have this case handled

### Version

1.1.9

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Non-Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
nvm install latest
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x1149e0c0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:790 +0x220
main.install({0x1140a0e0, 0x6}, {0x29fa65, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:302 +0x35d
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69
```

### Debug Output

```Shell
not supported for this version
```

**Comment by coreybutler** [comment]
This is already resolved in newer versions. We don't re-release older patched versions of NVM4W because we don't have the manpower to maintain every prior version as an independent workflow. This type of development model is not sustainable with NVM4W, but will be part of the [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) business model.

**Comment by Nasfame** [comment]
ok then it that case we just can take off the version support in the github bug template then?

**Comment by coreybutler** [comment]
The purpose of having the version listed in the github bug template is to identify when users need to update their installation, or to provide specific workarounds in the event they cannot update, so it's still relevant.
