### ISSUE TITLE
Why cann't successfully install in my win10 computer?

### ISSUE THREAD

**Issue by JackRo** [coreybutler/nvm-windows#158]
My Environment is Windows 10 chinese, but after i install the nvm for windows, i cann't find nodejs directory in "C:\Program Files", then after i install node version 5.9.1, i cann't run node in cmd, i show me a message which is "access is denied". so what should i do? could you tell me?

**Comment by coreybutler** [comment]
You probably need to run the command with admin privileges. Right click on the command prompt and select "Run As Administrator". After that, you will need to type `nvm use 5.9.1`. It should work after that.

**Comment by Chen188** [comment]
Also can't i finish the installation of sqlite3@3.1.2.

Env: win10 x64

I have tried to install this with command: npm install sqlite3 --build-from-source=sqlite3

Here is the error log:

```shell
E:\git\OJDisplay>npm install sqlite3 --build-from-source=sqlite3

> sqlite3@3.1.2 install E:\git\OJDisplay\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build


E:\git\OJDisplay\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\nvm\v5.9.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

E:\git\OJDisplay\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\nvm\v5.9.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=E:\git\OJDisplay\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\git\OJDisplay\node_modules\sqlite3\lib\binding\node-v47-win32-x64 )  else (node "" configure --fallback-to-build --module=E:\git\OJDisplay\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\git\OJDisplay\node_modules\sqlite3\lib\binding\node-v47-win32-x64 )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
gyp ERR! stack     at emitNone (events.js:80:13)
gyp ERR! stack     at TLSSocket.emit (events.js:179:7)
gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
gyp ERR! System Windows_NT 10.0.14291
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nvm\\v5.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\git\\OJDisplay\\node_modules\\sqlite3\\lib\\binding\\node-v47-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\git\\OJDisplay\\node_modules\\sqlite3\\lib\\binding\\node-v47-win32-x64"
gyp ERR! cwd E:\git\OJDisplay\node_modules\sqlite3
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=E:\git\OJDisplay\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\git\OJDisplay\node_modules\sqlite3\lib\binding\node-v47-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\git\OJDisplay\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.14291
node-pre-gyp ERR! command "C:\\nodejs\\node.exe" "E:\\git\\OJDisplay\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\git\OJDisplay\node_modules\sqlite3
node-pre-gyp ERR! node -v v5.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.24
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=E:\git\OJDisplay\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\git\OJDisplay\node_modules\sqlite3\lib\binding\node-v47-win32-x64' (1)
OJDisplay@0.0.0 E:\git\OJDisplay
`-- node-pre-gyp@0.6.24  extraneous

npm WARN In node-pre-gyp@0.6.24 replacing bundled version of minimist with minimist@0.0.8
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of abbrev with abbrev@1.0.7
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of ansi with ansi@0.3.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of delegates with delegates@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of core-util-is with core-util-is@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of inherits with inherits@2.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of isarray with isarray@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of process-nextick-args with process-nextick-args@1.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of string_decoder with string_decoder@0.10.31
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of util-deprecate with util-deprecate@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of has-unicode with has-unicode@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.repeat with lodash.repeat@4.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.tostring with lodash.tostring@4.1.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.repeat with lodash.repeat@4.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.tostring with lodash.tostring@4.1.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.repeat with lodash.repeat@4.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.tostring with lodash.tostring@4.1.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of deep-extend with deep-extend@0.4.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of ini with ini@1.3.4
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of minimist with minimist@1.2.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of strip-json-comments with strip-json-comments@1.0.4
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of aws-sign2 with aws-sign2@0.6.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of pseudomap with pseudomap@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of yallist with yallist@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of core-util-is with core-util-is@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of inherits with inherits@2.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of isarray with isarray@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of process-nextick-args with process-nextick-args@1.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of string_decoder with string_decoder@0.10.31
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of util-deprecate with util-deprecate@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of caseless with caseless@0.11.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of delayed-stream with delayed-stream@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of extend with extend@3.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of forever-agent with forever-agent@0.6.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of async with async@1.5.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of color-convert with color-convert@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of escape-string-regexp with escape-string-regexp@1.0.5
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of ansi-regex with ansi-regex@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of ansi-regex with ansi-regex@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of supports-color with supports-color@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of graceful-readlink with graceful-readlink@1.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of generate-function with generate-function@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of is-property with is-property@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of jsonpointer with jsonpointer@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of xtend with xtend@4.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of pinkie with pinkie@2.0.4
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of boom with boom@2.10.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of cryptiles with cryptiles@2.0.5
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of hoek with hoek@2.16.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of sntp with sntp@1.0.9
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of assert-plus with assert-plus@0.2.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of extsprintf with extsprintf@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of json-schema with json-schema@0.2.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of verror with verror@1.3.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of asn1 with asn1@0.2.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of assert-plus with assert-plus@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of ecc-jsbn with ecc-jsbn@0.1.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of jodid25519 with jodid25519@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of jsbn with jsbn@0.1.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of tweetnacl with tweetnacl@0.14.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of is-typedarray with is-typedarray@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of isstream with isstream@0.1.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of json-stringify-safe with json-stringify-safe@5.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of mime-db with mime-db@1.22.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of node-uuid with node-uuid@1.4.7
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of oauth-sign with oauth-sign@0.8.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of qs with qs@6.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of stringstream with stringstream@0.0.5
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of tough-cookie with tough-cookie@2.2.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of tunnel-agent with tunnel-agent@0.4.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of wrappy with wrappy@1.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of inherits with inherits@2.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of balanced-match with balanced-match@0.3.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of concat-map with concat-map@0.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of wrappy with wrappy@1.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of path-is-absolute with path-is-absolute@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of semver with semver@5.1.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of block-stream with block-stream@0.0.8
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of graceful-fs with graceful-fs@4.1.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of inherits with inherits@2.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of ms with ms@0.7.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of graceful-fs with graceful-fs@4.1.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of inherits with inherits@2.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of inherits with inherits@2.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of balanced-match with balanced-match@0.3.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of concat-map with concat-map@0.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of wrappy with wrappy@1.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of core-util-is with core-util-is@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of inherits with inherits@2.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of isarray with isarray@1.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of process-nextick-args with process-nextick-args@1.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of string_decoder with string_decoder@0.10.31
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of util-deprecate with util-deprecate@1.0.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of uid-number with uid-number@0.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of nopt with nopt@3.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.pad with lodash.pad@4.1.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.padend with lodash.padend@4.2.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lodash.padstart with lodash.padstart@4.2.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of strip-ansi with strip-ansi@3.0.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of has-ansi with has-ansi@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of generate-object-property with generate-object-property@1.2.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of commander with commander@2.9.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of pinkie-promise with pinkie-promise@2.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of ansi-styles with ansi-styles@2.2.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of mime-types with mime-types@2.1.10
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of dashdash with dashdash@1.13.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of fstream with fstream@1.0.8
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of debug with debug@2.2.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of fstream with fstream@1.0.8
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of mkdirp with mkdirp@0.5.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of readable-stream with readable-stream@2.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of rc with rc@1.1.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of lru-cache with lru-cache@4.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of combined-stream with combined-stream@1.0.5
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of form-data with form-data@1.0.0-rc4
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of readable-stream with readable-stream@2.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of inflight with inflight@1.0.4
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of brace-expansion with brace-expansion@1.1.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of once with once@1.3.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of once with once@1.3.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of readable-stream with readable-stream@2.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of brace-expansion with brace-expansion@1.1.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of jsprim with jsprim@1.2.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of hawk with hawk@3.1.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of gauge with gauge@1.2.7
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of chalk with chalk@1.1.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of is-my-json-valid with is-my-json-valid@2.13.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of minimatch with minimatch@3.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of sshpk with sshpk@1.7.4
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of tar with tar@2.2.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of minimatch with minimatch@3.0.0
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of aws4 with aws4@1.3.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of are-we-there-yet with are-we-there-yet@1.1.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of bl with bl@1.0.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of glob with glob@7.0.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of fstream-ignore with fstream-ignore@1.0.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of har-validator with har-validator@2.0.6
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of http-signature with http-signature@1.1.1
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of rimraf with rimraf@2.5.2
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of npmlog with npmlog@2.0.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of tar-pack with tar-pack@3.1.3
npm WARN In node-pre-gyp@0.6.24 replacing bundled version of request with request@2.69.0
npm ERR! Windows_NT 10.0.14291
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--build-from-source=sqlite3"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\git\OJDisplay\npm-debug.log
```

**Comment by coreybutler** [comment]
@Chen188 - Your sqlite issue is caused by [node-gyp](https://github.com/nodejs/node-gyp), not NVM for Windows. I suggest you post this problem in their issues.

**Comment by Chen188** [comment]
@coreybutler OK, thanks for your reply.
