### ISSUE TITLE
Cannot run nvm install on Windows 10 (runtime error)

### ISSUE THREAD

**Issue by schibsted-martin** [coreybutler/nvm-windows#166]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

Install a node version (4)

### Actual Behavior

```
nvm install 4
panic: runtime error: index out of range

goroutine 1 [running]:
_/C_/Users/Corey/Documents/workspace/nvm-windows/src/nvm/web.IsNode64bitAvailable(0x12416134, 0x1, 0x674700)
        C:/Users/Corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:153 +0x157
main.install(0x12416134, 0x1, 0x674700, 0x2)
        C:/Users/Corey/Documents/workspace/nvm-windows/src/nvm.go:171 +0x484
main.main()
        C:/Users/Corey/Documents/workspace/nvm-windows/src/nvm.go:65 +0x64e

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0x12468360)
        C:/Go/v1.4/src/net/http/transport.go:928 +0x7ba
created by net/http.(*Transport).dialConn
        C:/Go/v1.4/src/net/http/transport.go:660 +0xa45

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0x12468360)
        C:/Go/v1.4/src/net/http/transport.go:945 +0x31a
created by net/http.(*Transport).dialConn
        C:/Go/v1.4/src/net/http/transport.go:661 +0xa5a
```

### Steps to reproduce the problem:

- Download nvm-windows v1.1.0 installer
- Install it
- Open console (Admin)
- Run `nvm` to verify the command
- Run `nvm install 4`

**Comment by schibsted-martin** [comment]
Solved by specifying "4.4.4" instead.
