### ISSUE TITLE
npm fails: "Cannot find module 'semver' (node v8.4.0)

### ISSUE THREAD

**Issue by lfurzewaddock** [coreybutler/nvm-windows#302]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [ ] 1.1.6
- [X] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [X] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Return correct version number.

### Actual Behavior

module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\leofu\AppData\Roaming\nvm\nvm\v8.4.0\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\leofu\AppData\Roaming\nvm\nvm\v8.4.0\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

### Steps to reproduce the problem:

nvm install 8.4.0
nvm use 8.4.0
npm -v

**Comment by coreybutler** [comment]
This is an npm error, not entirely an NVM error. I'd suggest reinstalling node 8.4.0.... perhaps the npm download was bad or something was corrupted.

**Comment by Zorgatone** [comment]
@coreybutler It won't work, keeps failing even deactivating, uninstalling, manually removing the folder reinstalling and reactivating. Same error.

I even copied the npm's node_modules dependencies from another working normal installation of node 8.5.0 and still having troubles. Could you look more into it, and see what the problem is?

The nvm is a really handy tool but not working anymore, and it's a pity :(

**Comment by coreybutler** [comment]
Not sure what to tell you.... I can install `semver` just fine with the same setup.

![image](https://user-images.githubusercontent.com/770982/30876759-2c42aa5c-a2bd-11e7-8818-8b4a9a283210.png)

**Comment by Zorgatone** [comment]
@coreybutler just opened a new issue with the details

**Comment by Zorgatone** [comment]
My own environment and the steps I used to replicate the issue here (closed duplicate): #305

**Comment by roman-spiridonov** [comment]
Same on the latest 8.8.1.

**Comment by nmors** [comment]
thanks @roman-spiridonov just ran into the same bug on node 8.8.1 installed via nvm on windows and your workaround seems to do the job

**Comment by slandsaw** [comment]
Seems to have also worked using the latest version of node (9.1.0).

**Comment by frizadiga** [comment]
seems npm thats installed from npm doesnt compatible with the node itself, you must download the zip and replace the npm module like @roman-spiridonov suggested

**Comment by hyndsite** [comment]
@coreybutler is this not going to be addressed?  I am seeing the exact same error exactly - anything above =< 8.0.

Unfortunately, I can't run `npm i semver` I get the same error.

**Comment by hyndsite** [comment]
@roman-spiridonov I don't find that "npm" is a folder, but a file in the downloaded .zip.  Replacing it with the downloaded one doesn't seem to resolve the semver issues for me (I know others have been successful)

**Comment by talesporto** [comment]
I have the same problem.

The @roman-spiridonov 's workaround work for me.

```
node 8.9.1
npm 5.5.1
```

**Comment by powellian** [comment]
@hyndsite you need to look inside the **node_modules** directory - inside that is **npm** directory. Use that and it should work.

**Comment by hyndsite** [comment]
Thanks @powellian I found that yesterday and was going to post a new update to @roman-spiridonov message - that the correct path is` %APPDATA%/nvm/v8.8.1/node_modules/npm` 

The "npm" file in the /nvm/vx.x.x  path helped to confuse the matter.

**Comment by benavern** [comment]
Thank you, it works, But now I am wondering why is the package that nvm downloads & the one we download is different ?

**Comment by Akamaozu** [comment]
Same problem with 8.9.0 and @roman-spiridonov's workaround saved the day.

Like @benavern I'm curious why the package nvm installs is different from the one in the official repo.

**Comment by earth55** [comment]
Same on the latest 8.9.4.
The error was solved by deleting directory 'C:\Users\yourname\AppData\Roaming\nvm\v*' and re-executing 'nvm install'.

**Comment by apptaro** [comment]
## Solution:
If you encounter this issue and you're using Windows 10, enable long paths using Registry Editor or Local Group Policy Editor.

Ref: https://github.com/coreybutler/nvm-windows/issues/305#issuecomment-345024594
Ref: https://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx?f=255&MSPPError=-2147217396#maxpath

**Comment by jaxer** [comment]
alternative it to move nvm root. do `nvm root C:\nvm` before installing new node.
if already installed, then:
```
nvm uninstall 8.x.x
nvm root C:\nvm
nvm install 8.x.x
```

**Comment by codeshell** [comment]
I experienced the same problem (Error: Cannot find module 'semver').

Some hints to get you going:

File compare (using official zip file) showed that there are indeed > 4k files and folders missing under `node_modules\npm`. It looks like the unzipping is aborted. Checked for v8.9.1 and v8.9.4: all node_modules alphabetically behind `libnpx` are missing. Wouldn't be surprised if it relates to those ridiculously nested folder structure: `...\nvm\v8.9.4\node_modules\npm\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish\`

I took the current master of nvm-windows, added some debug information to the install function within `nvm.go`, compiled it (with Go 1.10 win x64) and exchanged the nvm.exe with the new one. Result:
* The npm zip file which is downloaded to the temp directory **_is_** in fact the official one. (@benavern , @Akamaozu )
* The zip file was fully extracted within the temp directory and moved to the version-specific folder. **No** missing files.

Now for the surprising part, as I tried finding the regression:
* Checked out tag 1.1.6, compiled (without any changes), replaced nvm.exe with the new one, deleted v8.9.4, ran nvm install 8.9.4 => successful, no missing files
* Checked out tag 1.1.5, compiled (without any changes), replaced nvm.exe with the new one, deleted v8.9.4, ran nvm install 8.9.4 => successful, no missing files
* Replaced nvm.exe with the original one from the official nvm-windows setup (1.1.5), deleted v8.9.4, ran nvm install 8.9.4 => still **error**, files missing.

It looks for me like there is an issue with the build process and/or environment.

Would be great if someone else could try if recreating the nvm.exe via build.bat or `go build src/nvm.go` solves the problem for him/her as well.

HTH, codeshell

**Comment by Lokeshnagarajan** [comment]
Delete npm folder from below folder
C:\Users\username\AppData\Roaming\npm
after install
npm install

**Comment by cooploops** [comment]
Just ran into this issue today and this worked for me.
1) Open a bash terminal
2) CD into C:\Users\[username]\AppData\Roaming\npm\node_modules\
3) should see a package.json
4) yarn install

**Comment by dev7ch** [comment]
helped me:
https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver

**Comment by kedarkolhatkar** [comment]
@codeshell Thanks for your analysis. I found the issue to be due to the long paths that are not supported on Windows. For me even after downloading npm zip file and replacing contents of C:\Users\yourname\AppData\Roaming\nvm\9.11.1\npm I got the error. In fact I could not copy all files from downloaded npm zip file due to long names.

To avoid this I uninstalled node version 9.11.1, then uninstalled nvm. Reinstalled nvm at C:\nvm. Now my normal 'nvm install 9.11.1' works just fine and 'npm' is also in good state confirmed by running 'npm -v'.

I know this is a pretty drastic fix but just need to do one time.

**Comment by maheshigunaratne** [comment]
I followed These steps and it solved my issue
1. uninstall Node.js 
2. Remove the content of the following folders
       C:\Users\<user-name>\AppData\Roaming\npm-cache
       C:\Users\<user-name>\AppData\Roaming\npm
       C:\Program Files\nodejs
3. Then again install Node _https://nodejs.org/en/_

**Comment by BoyanPalagachev** [comment]
installing the node through nvm 1.6.0 worked for me

**Comment by slandsaw** [comment]
In my case, the paths were just too long.  I chose c:\nvm as the install directory version manager and c:\nodejs for the symlink directory. That seemed to resolve the issue for me.

**Comment by leifurhauks** [comment]
I had the same problem with node v10.4.0 and the [workaround](https://github.com/coreybutler/nvm-windows/issues/302#issuecomment-340249164) from roman-spiridonov worked for me.

I had already removed `%AppData%\npm` etc. before installing nvm-windows.

**Comment by NicTorgersen** [comment]
Tried getting 10.4.1 up and running, had problems at first.

Got it to work after deleting the folder from install location manually and installing via `nvm` again. Not sure whether this is too long of a path (obviously not) `C:\Users\muser\AppData\Roaming\nvm\v10.4.1`.

**Comment by rgomez90** [comment]
Same problem with v10.5.0 and [roman-spiridonovs solution](https://github.com/coreybutler/nvm-windows/issues/302#issuecomment-340249164) worked for me as well.

**Comment by shadeofgod** [comment]
I have the same probem when have the latest node v10.6.0, then I just uninstalled it and switched to v8.11.3, problem solved.

I also tried download directly the npm-v6.1.0.zip, it do have some errors when unzipping.

**Comment by uilyam** [comment]
Experienced the same issue @shadeofgod with 10.6.0.  Switching to 8.11.3 solved it.

**Comment by PutziSan** [comment]
problem persists with 10.6.0-64bit for a complete clean first install. (no node/npm before). [ roman-spiridonovs solution ](https://github.com/coreybutler/nvm-windows/issues/302#issuecomment-340249164) continues to work (for me the npm-folder can now bew found in `[...node]\node_modules\npm`)

**Comment by nickcoad** [comment]
Why is this still an issue after almost an entire year?

**Comment by damianhofmannwork** [comment]
Just encountered this issue on Windows 10.

Enabling Win32 long paths fixed the issue. See [post](https://github.com/coreybutler/nvm-windows/issues/302#issuecomment-365858567) from @apptaro (2018-02-15)

I feel, `nvm` under Windows should issue warnings if long paths aren't enabled. `nvm install` also should not fail silently.

**Comment by GrahamTheCoder** [comment]
For me:
* nvm install 9.11.2 was the last version I found that worked through nvm.
* Overwriting with the zip file from the website works on any version.
* The long paths fix didn't seem to work (possibly I hadn't tried a machine restart after changing the registry setting though).

**Comment by GrahamTheCoder** [comment]
I believe @momochanmo had just forgotten to install the semver package in their project. It has the same error message but this is a totally different issue.

To recap: This thread is about the fact that nvm installs a corrupted version of npm with a missing/corrupted version of the semver package, which renders it inoperable. 

The most likely root cause suggested so far is that a [bug / behaviour change](https://github.com/golang/go/issues/14527) introduced into the Go compiler about 3 years ago causes an error that's being silently swallowed during installation. See https://github.com/coreybutler/nvm-windows/pull/370.

So if you know someone who works with Windows stuff and is enthusiastic about Go, now's a good time to tap them on the shoulder and offer them this excellent career development opportunity 😅

**Comment by Pimentelk** [comment]
> I followed These steps and it solved my issue
> 
> 1. uninstall Node.js
> 2. Remove the content of the following folders
>    C:\Users<user-name>\AppData\Roaming\npm-cache
>    C:\Users<user-name>\AppData\Roaming\npm
>    C:\Program Files\nodejs
> 3. Then again install Node _https://nodejs.org/en/_

Following this worked for me. You are a life saver!!!!! thanks <3

**Comment by ChipClark** [comment]
I am using NVM for Node versions 10.21.1, 10.23.0, 12.20.0, 14.15.4 

 - I cannot run "npm -v" 
 
 However, if I specify the actual location of npm - that works: 
 C:\Users\cclark\AppData\Roaming\nvm\v12.20.1\npm -v  
 
 I have tried: 
 
 1. delete directory of node version in C:\Users\cclark\AppData\Roaming\nvm\ 
 2. download zip file of node version from https://nodejs.org/download/release/v12.20.1/
 3. copy files from zip file to directory
 4. run 'nvm use 12.20.1' 
 
npm -v will not run - semver error

nvm version 1.1.7 
Windows version 10.0.17763
