### ISSUE TITLE
Empty node_modules

### ISSUE THREAD

**Issue by WhatAKitty** [coreybutler/nvm-windows#82]
I used command "node install latest"
But there is nothing in node_modules.

And how about this function https://github.com/hakobera/nvmw/pull/21

**Comment by coreybutler** [comment]
That's an invalid command.... specifically the `node` part. The function you reference in nvmw already exists in NVM for Windows. Just type `nvm install latest`.

**Comment by kumargauravin** [comment]
using nvm install latest, node_module is coming empty same for any version

C:\Users\kg833v>nvm install latest
Version 12.1.0 is already installed.

C:\Users\kg833v>nvm use 12.1.0
Now using node v12.1.0 (64-bit)

C:\Users\kg833v>npm install
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'c:\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'c:\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
