### ISSUE TITLE
panic: runtime error: slice bounds out of range [:4] with length 1

### ISSUE THREAD

**Issue by ETZRV** [coreybutler/nvm-windows#838]
I have installed the latest version of NVM for Windows (1.19).
Then I tried `nvm install 6.17.1`. 
It failed, probably because of proxy:
`Get "https://nodejs.org/dist/latest/SHASUMS256.txt": dial tcp 104.20.22.46:443: i/o timeout`.
Next I tried to setup the proxy by using `nvm proxy = proxy.address:proxy.port`.
Then I again used `nvm install 6.17.1`. 
Now I receive the following error:
`panic: runtime error: slice bounds out of range [:4] with length 1`
`goroutine 1 [running]:`
`main.setup()`
`        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:969 +0x718`
`main.main()`
`        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:81 +0x10d`

**Comment by ETZRV** [comment]
Double, pardon me. See https://github.com/coreybutler/nvm-windows/issues/507.
