### ISSUE TITLE
nvm-windows doesn't work with the latest lts version of node (node v18.15.0, npm v9.5.0)

### ISSUE THREAD

**Issue by kglundgren** [coreybutler/nvm-windows#944]
**Issue:**
After installing node v18.15.0 and trying to use npm, the following error occurs:
```
ERROR: npm v9.5.0 is known not to run on Node.js v18.15.0. You'll need to upgrade
to a newer Node.js version in order to use this version of npm. This version of
npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
can find the latest version at https://nodejs.org/.

ERROR:
C:\Users\Gustav\AppData\Roaming\nvm\v18.15.0\node_modules\npm\node_modules\@npmcli\arborist:1
../../workspaces/arborist
^

SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Gustav\AppData\Roaming\nvm\v18.15.0\node_modules\npm\lib\npm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

ERROR: npm v9.5.0 is known not to run on Node.js v18.15.0. You'll need to upgrade
to a newer Node.js version in order to use this version of npm. This version of
npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
can find the latest version at https://nodejs.org/.

ERROR:
C:\Users\Gustav\AppData\Roaming\nvm\v18.15.0\node_modules\npm\node_modules\@npmcli\arborist:1
../../workspaces/arborist
^

SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\Gustav\AppData\Roaming\nvm\v18.15.0\node_modules\npm\lib\npm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

**Version info:**
`node -v`: v18.15.0
`npm -v`: outputs the error above.

**How To Reproduce:**
1. Install the latest version of nvm-windows.
2. Run `nvm install 18.15.0`
3. Try any npm command, eg. `npm i -g tree-sitter`

**Expected Behavior:**
I expected npm to work as usual. 

**OS:** Windows 10

**Comment by coreybutler** [comment]
Did you run `nvm use 18.15.0` after installing?

**Comment by kglundgren** [comment]
Yes to both questions. 

It works after reinstalling nvm4w however... I must've done something wrong. Sorry.

**Comment by coreybutler** [comment]
No worries, glad it's working!
