### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by bitbegin** [coreybutler/nvm-windows#972]
### What happened?

PS D:\nodejs> nvm list
panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
nvm/web.SetMirrors({0xa09ab20, 0x0}, {0xa09ab3c, 0x3})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:52 +0x318
main.setup()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1324 +0x602
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:88 +0x182

### What did you expect to happen?

normal work

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Standard User, Elevated

### Is Developer Mode enabled?

Yes

**Comment by bitbegin** [comment]
PS D:\nodejs> nvm npm_mirror
panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
nvm/web.SetMirrors({0xa40eb90, 0x0}, {0xa40ebac, 0x3})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:52 +0x318
main.setup()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1324 +0x602
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:88 +0x182
PS D:\nodejs> nvm off
panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
nvm/web.SetMirrors({0xa00eb70, 0x0}, {0xa00eb8c, 0x3})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:52 +0x318
main.setup()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1324 +0x602
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:88 +0x182
PS D:\nodejs> nvm debug
panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
nvm/web.SetMirrors({0xa80eb70, 0x0}, {0xa80eb8c, 0x3})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:52 +0x318
main.setup()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1324 +0x602
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:88 +0x182
PS D:\nodejs> nvm current
panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
nvm/web.SetMirrors({0xa49ab20, 0x0}, {0xa49ab3c, 0x3})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:52 +0x318
main.setup()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1324 +0x602
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:88 +0x182
PS D:\nodejs>
PS D:\nodejs> nvm list
panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
nvm/web.SetMirrors({0xa09ab20, 0x0}, {0xa09ab3c, 0x3})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:52 +0x318
main.setup()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1324 +0x602
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:88 +0x182
PS D:\nodejs> nvm list available
panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
nvm/web.SetMirrors({0xa80eba0, 0x0}, {0xa80ebbc, 0x3})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:52 +0x318
main.setup()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1324 +0x602
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:88 +0x182
PS D:\nodejs>

**Comment by coreybutler** [comment]
Please confirm the version you're running by executing `nvm --version`. This issue looks like an issue from v1.1.10, which has been duplicated 10 or 11 times now, despite being fixed in v1.1.11.

**Comment by bitbegin** [comment]
i‘m sure 1.1.11

**Comment by coreybutler** [comment]
Did you have a mirror setup before or after running `nvm list`? Perhaps a proxy? Did you upgrade from a prior version, or was this a fresh installation? 

Bottom line: I need more to go on, because this isn't enough to recreate the error.

**Comment by bitbegin** [comment]
>> Did you have a mirror setup before or after running nvm list?
yes
>> Did you upgrade from a prior version, or was this a fresh installation?
update from 1.1.8

**Comment by coreybutler** [comment]
please run `nvm debug` and post the output here.

**Comment by bitbegin** [comment]
```
PS D:\tools> nvm debug
panic: runtime error: slice bounds out of range [:4] with length 3

goroutine 1 [running]:
nvm/web.SetMirrors({0xa09ab20, 0x0}, {0xa09ab3c, 0x3})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:52 +0x318
main.setup()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1324 +0x602
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:88 +0x182
PS D:\tools>
```

**Comment by coreybutler** [comment]
This tells me either you're actually running NVM 1.1.10 or there is something corrupted in your settings file. I'd recommend backing up your settings file and removing it. Then run `nvm list` or any other command. NVM4W will generate a new file.

**Comment by bathos** [comment]
I just encountered this only when trying to install node 20.0.0 specifically (19.9.0 did work). I can confirm that the issue was fixed for me by upgrading nvm-windows to 1.1.11 (I had been on 1.1.9).

**Comment by bitbegin** [comment]
reinstall 1.1.11, work ok
