### ISSUE TITLE
[Issue]: NVM install fails with a runtime error: index

### ISSUE THREAD

**Issue by henry-cotton** [coreybutler/nvm-windows#984]
### What happened?

Trying to run "nvm install latest" in Powershell gives the following error:

panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x11ccf0f0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:875 +0x220
main.install({0x11c140b0, 0x6}, {0x11b9d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:308 +0x337
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea

### What did you expect to happen?

I expected to get version 20 of node installed on my system

### Version

1.1.10

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x11ccf0f0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:875 +0x220
main.install({0x11c140b0, 0x6}, {0x11b9d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:308 +0x337
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea
```

### Debug Output

```Shell
Running version 1.1.10.

Usage:

  nvm arch                     : Show if node is running in 32 or 64 bit mode.
  nvm current                  : Display active version.
  nvm install <version> [arch] : The version can be a specific version, "latest" for the latest current version, or "lts" for the
                                 most recent LTS version. Optionally specify whether to install the 32 or 64 bit version (defaults
                                 to system arch). Set [arch] to "all" to install 32 AND 64 bit versions.
                                 Add --insecure to the end of this command to bypass SSL validation of the remote download server.
  nvm list [available]         : List the node.js installations. Type "available" at the end to see what can be installed. Aliased as ls.
  nvm on                       : Enable node.js version management.
  nvm off                      : Disable node.js version management.
  nvm proxy [url]              : Set a proxy to use for downloads. Leave [url] blank to see the current proxy.
                                 Set [url] to "none" to remove the proxy.
  nvm node_mirror [url]        : Set the node mirror. Defaults to https://nodejs.org/dist/. Leave [url] blank to use default url.
  nvm npm_mirror [url]         : Set the npm mirror. Defaults to https://github.com/npm/cli/archive/. Leave [url] blank to default url.
  nvm uninstall <version>      : The version must be a specific version.
  nvm use [version] [arch]     : Switch to use the specified version. Optionally use "latest", "lts", or "newest".
                                 "newest" is the latest installed version. Optionally specify 32/64bit architecture.
                                 nvm use <arch> will continue using the selected version, but switch to 32/64 bit mode.
  nvm root [path]              : Set the directory where nvm should store different versions of node.js.
                                 If <path> is not set, the current root will be displayed.
  nvm [--]version              : Displays the current running version of nvm for Windows. Aliased as v.
```

**Comment by WORMSS** [comment]
Thank you.. This confused me, I thought I was typing numbers incorrectly 4 times.. LOL

**Comment by cobbvanth** [comment]
> Upgrade to [v1.1.11](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.11). When Node released v19, they quietly added a new ARM installer that breaks the regex pattern used to identify the appropriate file. This is accounted for in v1.1.11+.

Thanks, this is the proper fix for anyone who stumbles across the same issue :)

**Comment by robozb** [comment]
> Upgrade to [v1.1.11](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.11). When Node released v19, they quietly added a new ARM installer that breaks the regex pattern used to identify the appropriate file. This is accounted for in v1.1.11+.

Dear @coreybutler,

How can you upgrade nvm-windows?

Thanks!

Bela

**Comment by WORMSS** [comment]
@robozb https://github.com/coreybutler/nvm-windows#upgrading-nvm-windows

Literally on the FIRST PAGE of the whole repo.

**Comment by robozb** [comment]
> @robozb https://github.com/coreybutler/nvm-windows#upgrading-nvm-windows
> 
> Literally on the FIRST PAGE of the whole repo.

You are really kind! Thank you so much for your quick answer!
